dist: focal
sudo: true
language: python
python:
    - "3.9"

before_install:
    - sudo apt-get install libgeos-dev libproj-dev proj-data graphviz libblas-dev liblapack-dev

install:
    - pip install -r requirements_conda.txt
    - pip install -r requirements.txt
    - pip uninstall -y shapely
    - pip install --no-binary shapely shapely

script:
    - python ./setup.py unittests
